# Usa una imagen base adecuada
FROM node:18-alpine

# Crea el directorio de la app
WORKDIR /usr/src/app

# Copia el package.json y package-lock.json
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Compila (si es NestJS en producción)
RUN npm run build

# Usa el puerto que Cloud Run espera
ENV PORT=8080

# Expón el puerto 8080
EXPOSE 8080

# Comando para iniciar tu app
CMD ["npm", "run", "start:prod"]
