# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nestprueba

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --if-present

      - name: Build application
        run: npm run build

      - name: Create deployment package
        run: |
          # Crear directorio para el paquete de despliegue
          mkdir deployment-package
          
          # Copiar archivos necesarios para producción
          cp -r dist/ deployment-package/
          cp -r node_modules/ deployment-package/
          cp package*.json deployment-package/
          
          # Si tienes archivos estáticos o de configuración
          if [ -d "public" ]; then
            cp -r public/ deployment-package/
          fi
          
          # Crear el zip desde el directorio de despliegue
          cd deployment-package
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D0ABA36FDA5412F9F1B4FBDA4918C33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4EECF4674B1A4AB5A6069A59D7BE519B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E2C172574E5F42468B7A3B06915C7E79 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nestprueba'
          slot-name: 'Production'
          package: .
          clean: true
          restart: true
          enable-oryx-build: false